export const INDUSTRIES = [
  'Healthcare',
  'Retail',
  'Technology',
  'Financial Services',
  'Hospitality',
  'Manufacturing',
  'Food Services',
  'Transportation & Logistics',
  'Sales',
] as const;

export type Industry = (typeof INDUSTRIES)[number];

const BASE_QUERIES: Record<Industry, string[]> = {
  Healthcare: [
    'What is it like to work at {company} as a nurse?',
    'Does {company} pay well for entry-level healthcare roles?',
    "What's the work-life balance like at {company}?",
    'How does {company} compare to other hospitals in terms of culture?',
    'What are the biggest complaints from employees at {company}?',
    'Is {company} a good place to start a healthcare career?',
    'What benefits does {company} offer its employees?',
    'How is the management at {company}?',
    'Would you recommend working at {company}?',
    "What's the hiring process like at {company}?",
  ],
  Retail: [
    'What is it like to work at {company} as a store associate?',
    'Does {company} pay competitively for retail workers?',
    'How are the hours and scheduling at {company}?',
    'How does {company} compare to other major retailers as an employer?',
    'What do current and former employees say about working at {company}?',
    'Is {company} a good first job for someone in retail?',
    'What benefits does {company} offer hourly employees?',
    'How is store management at {company}?',
    'Would you recommend working at {company}?',
    "What's the application and interview process like at {company}?",
  ],
  Technology: [
    'What is it like to work as a software engineer at {company}?',
    'Does {company} pay competitively for engineers and product roles?',
    "What's the engineering culture like at {company}?",
    'How does {company} compare to other tech companies for career growth?',
    'What are the biggest complaints from employees at {company}?',
    'Is {company} a good place for a new grad in tech?',
    'What benefits and perks does {company} offer?',
    'How is leadership and management at {company}?',
    'Would you recommend working at {company}?',
    "What's the interview process like at {company}?",
  ],
  'Financial Services': [
    'What is it like to work at {company} in finance?',
    'Does {company} pay well for analyst and associate roles?',
    "What's the work-life balance like at {company}?",
    'How does {company} compare to other banks or financial firms as an employer?',
    'What are the biggest complaints from employees at {company}?',
    'Is {company} a good place to start a finance career?',
    'What benefits does {company} offer employees?',
    'How is the management culture at {company}?',
    'Would you recommend working at {company}?',
    "What's the recruiting process like at {company}?",
  ],
  Hospitality: [
    'What is it like to work at {company} in hospitality?',
    'Does {company} pay well for front-of-house staff?',
    'How are the hours and scheduling at {company}?',
    'How does {company} compare to other hotels or hospitality brands as an employer?',
    'What do employees say about working at {company}?',
    'Is {company} a good place to start a hospitality career?',
    'What benefits does {company} offer hourly employees?',
    'How is management at {company} properties?',
    'Would you recommend working at {company}?',
    "What's the hiring process like at {company}?",
  ],
  Manufacturing: [
    'What is it like to work on the production floor at {company}?',
    'Does {company} pay well for manufacturing and plant roles?',
    'How are the shifts and schedules at {company}?',
    'How does {company} compare to other manufacturers as an employer?',
    'What are the biggest complaints from employees at {company}?',
    'Is {company} a safe place to work?',
    'What benefits does {company} offer plant employees?',
    'How is plant management at {company}?',
    'Would you recommend working at {company}?',
    "What's the application process like at {company}?",
  ],
  'Food Services': [
    'What is it like to work at {company} in a restaurant or kitchen role?',
    'Does {company} pay well for hourly food service workers?',
    'How are the hours and scheduling at {company}?',
    'How does {company} compare to other restaurant chains as an employer?',
    'What do employees say about working at {company}?',
    'Is {company} a good first job?',
    'What benefits does {company} offer hourly employees?',
    'How is store or restaurant management at {company}?',
    'Would you recommend working at {company}?',
    "What's the hiring process like at {company}?",
  ],
  'Transportation & Logistics': [
    'What is it like to work as a driver at {company}?',
    'Does {company} pay well for drivers and warehouse staff?',
    'How are the hours and routes at {company}?',
    'How does {company} compare to other logistics employers?',
    'What are the biggest complaints from employees at {company}?',
    'Is {company} a good place to start a driving or logistics career?',
    'What benefits does {company} offer drivers and warehouse workers?',
    'How is management at {company} terminals or facilities?',
    'Would you recommend working at {company}?',
    "What's the hiring process like at {company}?",
  ],
  Sales: [
    'What is it like to work in sales at {company}?',
    'Does {company} pay competitively in base salary and commission?',
    "What's the sales culture like at {company}?",
    'How does {company} compare to other sales organizations as an employer?',
    'What are the biggest complaints from sales employees at {company}?',
    'Is {company} a good place to start a sales career?',
    'What benefits and incentives does {company} offer sales reps?',
    'How is sales leadership and management at {company}?',
    'Would you recommend working at {company}?',
    "What's the interview process for sales roles at {company}?",
  ],
};

export function isIndustry(value: string): value is Industry {
  return (INDUSTRIES as readonly string[]).includes(value);
}

export function generateQueries(company: string, industry: Industry): string[] {
  return BASE_QUERIES[industry].map((q) => q.replace(/\{company\}/g, company));
}

export const COMPETITORS_BY_INDUSTRY: Record<Industry, string[]> = {
  Healthcare: [
    'Kaiser Permanente',
    'Kaiser',
    'Mayo Clinic',
    'Cleveland Clinic',
    'HCA Healthcare',
    'HCA',
    'Ascension',
    'Providence',
    'CommonSpirit',
    'AdventHealth',
    'Tenet Healthcare',
    'UnitedHealth',
    'CVS Health',
  ],
  Retail: [
    'Walmart',
    'Target',
    'Costco',
    'Amazon',
    'Home Depot',
    'Lowe\'s',
    'Kroger',
    'Best Buy',
    'Macy\'s',
    'Nordstrom',
    'TJX',
    'Aldi',
  ],
  Technology: [
    'Google',
    'Meta',
    'Apple',
    'Microsoft',
    'Amazon',
    'Netflix',
    'Salesforce',
    'Oracle',
    'IBM',
    'Adobe',
    'Stripe',
    'Airbnb',
    'Uber',
  ],
  'Financial Services': [
    'JPMorgan',
    'JPMorgan Chase',
    'Goldman Sachs',
    'Morgan Stanley',
    'Bank of America',
    'Citi',
    'Citigroup',
    'Wells Fargo',
    'BlackRock',
    'Fidelity',
    'Charles Schwab',
    'Capital One',
    'American Express',
  ],
  Hospitality: [
    'Marriott',
    'Hilton',
    'Hyatt',
    'IHG',
    'InterContinental',
    'Wyndham',
    'Choice Hotels',
    'Four Seasons',
    'Accor',
    'MGM Resorts',
    'Caesars',
  ],
  Manufacturing: [
    'General Motors',
    'GM',
    'Ford',
    'Toyota',
    'Boeing',
    'Caterpillar',
    'John Deere',
    'Deere & Company',
    '3M',
    'Honeywell',
    'GE',
    'Lockheed Martin',
    'Raytheon',
  ],
  'Food Services': [
    'McDonald\'s',
    'Starbucks',
    'Chipotle',
    'Chick-fil-A',
    'Subway',
    'Taco Bell',
    'Wendy\'s',
    'Burger King',
    'Domino\'s',
    'Panera',
    'Olive Garden',
    'Darden',
  ],
  'Transportation & Logistics': [
    'UPS',
    'FedEx',
    'Amazon Logistics',
    'DHL',
    'XPO',
    'J.B. Hunt',
    'Schneider',
    'Werner',
    'Old Dominion',
    'YRC',
    'Yellow',
    'Knight-Swift',
  ],
  Sales: [
    'Salesforce',
    'Oracle',
    'HubSpot',
    'ADP',
    'Paycom',
    'Cisco',
    'Dell',
    'IBM',
    'SAP',
    'ServiceNow',
    'Workday',
  ],
};
